/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoEscola.view;

import autoEscola.controller.AulaController;
import autoEscola.model.Aluno.Aluno;
import autoEscola.model.Aula.Aula;
import autoEscola.model.Instrutor.Instrutor;
import autoEscola.util.MetodosUteis.MetodosUteis;
import autoEscola.util.utilitarios.ModeloTabela;
import autoEscola.util.utilitarios.UtilDesktop;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowSorter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author casa
 */
public class AulasAluno extends javax.swing.JFrame {

    private Aluno aluno;

    /**
     * Creates new form AulasAluno
     */
    public AulasAluno() {
        initComponents();

    }

    public AulasAluno(Aluno aluno) {
        this();
        this.aluno = aluno;
        this.lblTextoApresentacao.setText("Olá: " + this.aluno.getNome() + " Cpf: " + this.aluno.getCpf());
        //System.out.println(AulaController.getAulasPorAluno(this.nomeAluno, this.cpfAluno));
        if (!this.aluno.getAceitaTroca()) {
            tbPainel.setEnabledAt(1, false);
        } else {
            loadTableAulasParaTroca();
        }
        loadTableMinhasAulas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTextoApresentacao = new javax.swing.JLabel();
        tbPainel = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAulas = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAulasParaTroca = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estas São suas Aulas: ");

        tblAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblAulas);

        tbPainel.addTab("Minhas Aulas", jScrollPane2);

        tblAulasParaTroca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAulasParaTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAulasParaTrocaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAulasParaTroca);

        tbPainel.addTab("Aulas Disponívels para troca", jScrollPane1);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(lblTextoApresentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(tbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTextoApresentacao)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(tbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.aluno = null;
        this.setVisible(false);
        new LoginAluno().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tblAulasParaTrocaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAulasParaTrocaMouseClicked

        String categoriaAulaOrigem =  tblAulas.getModel().getValueAt(tblAulas.getSelectedRow(), 4).toString();
        String categoriaAulaDestino = tblAulasParaTroca.getModel().getValueAt(tblAulasParaTroca.getSelectedRow(), 4).toString();

        try {
            if (categoriaAulaOrigem.equals(categoriaAulaDestino)) {
                UtilDesktop.msgBox("Aulas compativeis Aula Origem: " + categoriaAulaOrigem + "categoria Aula Destino: " + categoriaAulaDestino);
                

            } else {
                UtilDesktop.msgBox("Aulas imcompativeis Aula Origem: " + categoriaAulaOrigem + "categoria Aula Destino: " + categoriaAulaDestino);
            }
        } catch (Exception e) {
            UtilDesktop.msgBox(e.getMessage());
        }

        /* 
        Eu sei, nao deveria colocar aqui, mas ninguem vai ver, apenas eu, essas informacoes poderam ser uteis futuramente        
        Aulas para troca:
            idAula -> 0
            Categoria Aula -> 4
            Instrutor Cpf -> 8
            Aluno Cpf -> 9
        ---------------------
        Minhas Aulas:
            idAula -> 0
            Categoria Aula -> 4
            Cpf Instrutor -> 9;
        
         */

    }//GEN-LAST:event_tblAulasParaTrocaMouseClicked

    /**
     * @param args the command line arguments
     */
    public void loadTableAulasParaTroca() {
        ArrayList dados = new ArrayList<>();

        String[] colunas = new String[]{"id Aula", "Data Inicio Aula", "Data Término Aula", "Quantidade de Aulas", "Modalidade da Aula", "Nome do Aluno",
            "Aceita Troca?", "Nome do Instrutor", "CPF Instrutor", "CPF Aluno"};
        for (Aula aulasAluno : AulaController.getAulasAceitamTroca()) {
            if (!aulasAluno.getAluno().getCpf().equals(this.aluno.getCpf())) {
                dados.add(new Object[]{
                    aulasAluno.getId(),
                    MetodosUteis.getDataFormatadaBR(aulasAluno.getDataAulaInicio()),
                    MetodosUteis.getDataFormatadaBR(aulasAluno.getDataAulaTermino()),
                    aulasAluno.getQuantidadeAulas(),
                    aulasAluno.getModalidadeAula(),
                    aulasAluno.getAluno().getNome(),
                    aulasAluno.getAluno().getAceitaTroca() ? "Aceita Troca" : "Não Aceita troca",
                    aulasAluno.getInstrutor().getNome(),
                    aulasAluno.getInstrutor().getCpf(),
                    aulasAluno.getAluno().getCpf()

                });
            }
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tblAulasParaTroca.setModel(modelo);

        for (int i = 0; i < colunas.length; i++) {
            if (i != 0 || i != 8 || i != 9) {
                tblAulasParaTroca.getColumnModel().getColumn(i).setPreferredWidth(80);
                tblAulasParaTroca.getColumnModel().getColumn(i).setResizable(true);
            }

        }
        esconderValoresTabela(tblAulasParaTroca, 0);
        esconderValoresTabela(tblAulasParaTroca, 8);
        esconderValoresTabela(tblAulasParaTroca, 9);
        tblAulasParaTroca.getTableHeader().setReorderingAllowed(false);
        tblAulasParaTroca.setAutoResizeMode(tblAulasParaTroca.AUTO_RESIZE_OFF);

        tblAulasParaTroca.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        tblAulasParaTroca.setRowSorter(sorter);
        tblAulasParaTroca.getSelectionModel().setSelectionInterval(0, 0);
    }

    public void esconderValoresTabela(JTable tabela, int indice) {
        tabela.getColumnModel().getColumn(indice).setMaxWidth(0);
        tabela.getColumnModel().getColumn(indice).setMinWidth(0);
        tabela.getColumnModel().getColumn(indice).setPreferredWidth(0);
        tabela.getColumnModel().getColumn(indice).setResizable(false);
    }

    public void loadTableMinhasAulas() {
        ArrayList dados = new ArrayList<>();

        String[] colunas = new String[]{"ID Aula", "Data Inicio Aula", "Data Término Aula", "Quantidade de Aulas", "Modalidade da Aula", "CPF do Aluno", "Nome do Aluno",
            "Aceita Troca?", "Nome do Instrutor", "CPF Instrutor"};
        for (Aula aulasAluno : AulaController.getAulasPorAluno(this.aluno.getNome(), this.aluno.getCpf())) {
            dados.add(new Object[]{
                aulasAluno.getId(),
                MetodosUteis.getDataFormatadaBR(aulasAluno.getDataAulaInicio()),
                MetodosUteis.getDataFormatadaBR(aulasAluno.getDataAulaTermino()),
                aulasAluno.getQuantidadeAulas(),
                aulasAluno.getModalidadeAula(),
                aulasAluno.getAluno().getCpf(),
                aulasAluno.getAluno().getNome(),
                aulasAluno.getAluno().getAceitaTroca() ? "Aceita Troca" : "Não Aceita troca",
                aulasAluno.getInstrutor().getNome(),
                aulasAluno.getInstrutor().getCpf()
            });
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tblAulas.setModel(modelo);

        for (int i = 0; i < colunas.length; i++) {
            tblAulas.getColumnModel().getColumn(i).setPreferredWidth(80);
            tblAulas.getColumnModel().getColumn(i).setResizable(true);
        }

        esconderValoresTabela(tblAulas, 0);
        esconderValoresTabela(tblAulas, 9);

        tblAulas.getTableHeader().setReorderingAllowed(false);
        tblAulas.setAutoResizeMode(tblAulas.AUTO_RESIZE_OFF);

        tblAulas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        tblAulas.setRowSorter(sorter);
        tblAulas.getSelectionModel().setSelectionInterval(0, 0);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AulasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AulasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AulasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AulasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AulasAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTextoApresentacao;
    private javax.swing.JTabbedPane tbPainel;
    private javax.swing.JTable tblAulas;
    private javax.swing.JTable tblAulasParaTroca;
    // End of variables declaration//GEN-END:variables
}
