/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoEscola.view;

import autoEscola.controller.AulaController;
import autoEscola.model.Aula.Aula;
import autoEscola.util.utilitarios.ModeloTabela;
import autoEscola.util.validacoes.validaCPF.ValidaCPF;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author casa
 */
public class AulasAluno extends javax.swing.JFrame {

    private String nomeAluno, cpfAluno;

    /**
     * Creates new form AulasAluno
     */
    public AulasAluno() {
        initComponents();   
        //System.out.println(AulaController.getAulasPorAluno("Eduardo Valois Franz", "101.189.169-71"));
    }

    public AulasAluno(String nome, String cpf) {      
        this();
        this.nomeAluno = nome;
        this.cpfAluno = ValidaCPF.imprimeCPF(cpf);
        //System.out.println(AulaController.getAulasPorAluno(this.nomeAluno, this.cpfAluno));
        LoadTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAulas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estas São suas Aulas: ");

        tblAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblAulas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void LoadTable(){
        ArrayList dados = new ArrayList<>();
        
        
        String[] colunas = new String[]{"dataAulaInicio", "dataAulaTermino", "quantidadeAula", "modalidadeAula", "cpfAluno", "nomeAluno", "aceitaTroca" ,"nomeInstrutor"};
        for(Aula aulasAluno : AulaController.getAulasPorAluno(this.nomeAluno, this.cpfAluno)){
            dados.add(new Object[]{
                    aulasAluno.getDataAulaInicio(),
                    aulasAluno.getDataAulaTermino(),
                    aulasAluno.getQuantidadeAulas(),
                    aulasAluno.getModalidadeAula(),
                    aulasAluno.getAluno().getCpf(),
                    aulasAluno.getAluno().getNome(),
                    aulasAluno.getAluno().getAceitaTroca(),
                    aulasAluno.getInstrutor().getNome()
            });
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tblAulas.setModel(modelo);
        
        for(int i = 0; i < colunas.length; i++){
            tblAulas.getColumnModel().getColumn(i).setPreferredWidth(80);
            tblAulas.getColumnModel().getColumn(i).setResizable(true);
        }
        tblAulas.getTableHeader().setReorderingAllowed(false);
        tblAulas.setAutoResizeMode(tblAulas.AUTO_RESIZE_OFF);
        
        tblAulas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                           
                
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AulasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AulasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AulasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AulasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AulasAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAulas;
    // End of variables declaration//GEN-END:variables
}
