/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoEscola.view;

import autoEscola.controller.InstrutorController;
import autoEscola.model.Instrutor.Instrutor;
import autoEscola.util.validacoes.validaCPF.ValidaCPF;
import autoEscola.util.validacoes.validacoesDataBase.ValidacoesBancoDeDados;
import autoEscola.util.validacoes.validacoesGerais.ValidacoesGerais;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author duduf
 */
public class CadastroInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroInstrutor
     */
    public CadastroInstrutor() {
        initComponents();
    }
    private static Boolean registroValido = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeInstrutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCpfInstrutor = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Instrutor");

        jLabel2.setText("Nome instrutor: ");

        txtNomeInstrutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeInstrutorFocusLost(evt);
            }
        });

        jLabel3.setText("CPF Instrutor");

        txtCpfInstrutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfInstrutorFocusLost(evt);
            }
        });

        btnSalvar.setText("Salvar Registro");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar para o Menu");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCpfInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar)))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpfInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfInstrutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfInstrutorFocusLost
        // TODO add your handling code here:
        String cpfInstrutor = txtCpfInstrutor.getText();
        if (!ValidaCPF.isCPF(cpfInstrutor)) {
            //btnSalvar.setEnabled(true);           
            JOptionPane.showMessageDialog(null, "CPF ENCONTRA-SE INVALIDO", "ERRO NO CPF", JOptionPane.WARNING_MESSAGE);            
        } else if (ValidacoesBancoDeDados.cpfExistenteDataBaseInstrutor(cpfInstrutor)) {
            JOptionPane.showMessageDialog(null, "CPF JÁ ENCONTRA-SE REGISTRADO", "CPF EXISTENTE", JOptionPane.WARNING_MESSAGE);            
        }
        
    }//GEN-LAST:event_txtCpfInstrutorFocusLost

    private void txtNomeInstrutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeInstrutorFocusLost
        String nomeInstrutor = txtNomeInstrutor.getText();
        if (nomeInstrutor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome encontra-se vazio, digite novamente", "NOME INVÁLIDO", JOptionPane.WARNING_MESSAGE);
            
        } else if (nomeInstrutor.length() > 30) {
            JOptionPane.showMessageDialog(null, "Nome Invalido, digite novamente", "NOME INVÁLIDO", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_txtNomeInstrutorFocusLost

    
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String nomeInstrutor = txtNomeInstrutor.getText();
        String cpfInstrutor = txtCpfInstrutor.getText();
        if(!ValidacoesGerais.instrutorIsValido(cpfInstrutor, nomeInstrutor)){
            btnSalvar.setEnabled(false);
        }else{
            btnSalvar.setEnabled(true);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        // TODO add your handling code here:
        String nomeInstrutor = txtNomeInstrutor.getText();
        String cpfInstrutor = txtCpfInstrutor.getText();
        if(!ValidacoesGerais.instrutorIsValido(cpfInstrutor, nomeInstrutor)){
            btnSalvar.setEnabled(false);
        }else{
            btnSalvar.setEnabled(true);
        }
        
        try {
            InstrutorController.addInstrutor(new Instrutor(nomeInstrutor, cpfInstrutor));
        } catch (Exception ex) {
            this.btnSalvar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Registro com informações incorretas", "REGISTRO COM DADOS INCONSCISTENTES", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
        new HomeAutoEscola().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCpfInstrutor;
    private javax.swing.JTextField txtNomeInstrutor;
    // End of variables declaration//GEN-END:variables
}
